# Generated by Django 4.2.1 on 2023-09-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
